In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\Documents\ml pojects\Movie_classification.csv")

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# Missing value imputation

In [6]:
df['Time_taken'].mean()

157.3914979757085

In [7]:
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22792\1486983121.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace=True)


In [8]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# Dummy varible creation 

In [10]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [11]:
df = pd.get_dummies(df, columns = ["3D_available", "Genre"], drop_first = True , dtype = int)

In [12]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

# X - y split

In [14]:
X = df.loc[:, df.columns != "Start_Tech_Oscar"]
type(X)

pandas.core.frame.DataFrame

In [15]:
X.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

In [16]:
X.shape

(506, 20)

In [17]:
y = df["Start_Tech_Oscar"]

In [18]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [19]:
y.shape

(506,)

# test-train split

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2)

In [23]:
X_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
139            30.8904               98.78               0.376  34168.805   
29             40.0490               71.28               0.462  37074.070   
128            26.5086               98.78               0.376  35724.205   
504            22.1918               78.86               0.427  37740.670   
386           507.8760               91.20               0.300  25841.860   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
139         171.4               9.045                9.205             9.16   
29          160.8               7.735                8.030             7.82   
128         172.3               9.020                9.195             9.04   
504         162.8               8.730                8.845             8.80   
386         173.5               9.145                9.320             9.14   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
139            9.255           7.76         411330      173.12   
29             7.935           6.80         466851      180.40   
128            9.115           7.76         444896      163.20   
504            8.845           6.80         496077      158.80   
386            9.460           7.96         291349      154.20   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
139          202.848              29            592       35600   
29           243.360              50            488       42000   
128          282.880              41            564       36000   
504          303.520              47            607       44000   
386          301.680              34            597       21000   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
139                 1             0            1               0  
29                  0             0            0               1  
128                 0             1            0               0  
504                 1             1            0               0  
386                 1             0            0               1

In [24]:
X_train.shape


(404, 20)

In [25]:
X_test.shape

(102, 20)

# training classification

In [27]:
from sklearn import tree
clftree = tree.DecisionTreeClassifier(max_depth=3)

In [28]:
clftree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3)

# predict values using trained model

In [30]:
y_train_pred = clftree.predict(X_train)
y_test_pred = clftree.predict(X_test)

# model performance

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [33]:
confusion_matrix(y_train,y_train_pred)

array([[189,   2],
       [143,  70]], dtype=int64)

In [34]:
confusion_matrix(y_test,y_test_pred)

array([[36,  3],
       [50, 13]], dtype=int64)

In [35]:
accuracy_score(y_test,y_test_pred)

0.4803921568627451

# plotting


In [37]:
dot_data = tree.export_graphviz(clftree, out_file=None,feature_names= X_train.columns, filled = True)

In [38]:
from IPython.display import Image

In [39]:
import pydotplus


In [40]:
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [41]:
conda install python-graphviz

error: incomplete escape \U at position 28

# bagging


In [43]:
clftree = tree.DecisionTreeClassifier()

In [45]:
from sklearn.ensemble import BaggingClassifier

In [47]:
bag_clf = BaggingClassifier(clftree, n_estimators=1000, bootstrap =True, n_jobs= -1, random_state=42 )

In [49]:
bag_clf.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=1000,
                  n_jobs=-1, random_state=42)

In [51]:
confusion_matrix(y_test, bag_clf.predict(X_test))

array([[21, 18],
       [27, 36]], dtype=int64)

In [53]:
accuracy_score(y_test, bag_clf.predict(X_test))

0.5588235294117647

# random forest

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [67]:
rf_clf = RandomForestClassifier(n_estimators=1000,n_jobs = -1, random_state = 42 )

In [69]:
rf_clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1000, n_jobs=-1, random_state=42)

In [71]:
confusion_matrix(y_test,rf_clf.predict(X_test))

array([[21, 18],
       [26, 37]], dtype=int64)

In [73]:
accuracy_score(y_test,rf_clf.predict(X_test))

0.5686274509803921

# grid search

In [80]:
from sklearn.model_selection import GridSearchCV

In [82]:
rf_clf = RandomForestClassifier(n_estimators=250, random_state = 42 )

In [84]:
params_grid = {
    "max_features" : [4,5,6,7,8,9,10],
    "min_samples_split" : [2,3,10]
}

In [86]:
grid_search = GridSearchCV(rf_clf, params_grid, n_jobs=-1,cv =5 ,scoring = "accuracy") #cv - cross validation

In [88]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(n_estimators=250,
                                              random_state=42),
             n_jobs=-1,
             param_grid={'max_features': [4, 5, 6, 7, 8, 9, 10],
                         'min_samples_split': [2, 3, 10]},
             scoring='accuracy')

In [90]:
grid_search.best_params_

{'max_features': 10, 'min_samples_split': 2}

In [92]:
cvrf_clf = grid_search.best_estimator_

In [96]:
accuracy_score(y_test , cvrf_clf.predict(X_test))

0.5882352941176471

In [98]:
confusion_matrix(y_test , cvrf_clf.predict(X_test))

array([[21, 18],
       [24, 39]], dtype=int64)